site_name: krangl - {k}otlin data w{rangl}ing made easy

site_url: https://github.com/holgerbrandl/krangl
site_author: Holger Brandl
site_description: >-
  krangl is a Kotlin library for data wrangling. By implementing a grammar of data manipulation using a modern functional-style API, it allows to filter, transform, aggregate and reshape tabular data.
repo_name: holgerbrandl/krangl
repo_url: https://github.com/holgerbrandl/krangl
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Holger Brandl

theme:
  name: material
#  highlightjs: true
#  hljs_languages:
#    - kotlin
#  navigation_depth: 3
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tabs

nav:
  - Getting Started:
    - Introduction: index.md
    - 10 Minute Tutorial: 10_minutes.md
    - F.A.Q: faq.md
    - External:
      - API Docs : apidocs.md
      - Github Project Page: "https://github.com/holgerbrandl/krangl"
      - Change Log: "https://github.com/holgerbrandl/krangl/blob/master/CHANGES.md"
      - Report a Problem: "https://github.com/holgerbrandl/krangl/issues"
      - Discussion Forum: "https://gitter.im/holgerbrandl/krangl"

  - Concepts:
    - Data Model: data_model.md
    - Data Manipulation: data_manip.md
    - Reshape Tabular Data: reshape.md

  - Tutorials:
    - Regression Analysis: tutorials/statistics.md
    - Machine Learning: tutorials/statistics.md#machine_learning_with_smile
    - Reportin Rendering: tutorials/report_rendering.md
    - Data Visualization: tutorials/data_vis.md
    - Time Series: time-series.md

  - About:
    - about.md


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/holgerbrandl
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/holgerbrandl/krangl
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/holgerbrandl
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/holgerbrandl/

markdown_extensions:
  - markdown_include.include:
      base_path: examples/kotlin
  - pymdownx.highlight:
#      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - admonition

            #extra_css:
          #  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js
